### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by saujashb** [DrGFreeman/IFTTT-Webhook#1]
Even after successfully running the pip install, my program outputs a ModuleNotFoundError for 'ifttt_webhook'

**Comment by DrGFreeman** [comment]
Hi @juice2104, this seems like an issue with your Python / pip environment, not with the package. A few tips I can give you:
- Ensure you have git installed, it is required to use pip with `git+https` type reference.
- Use `python -m pip` instead of just `pip`.
- Run `python -m pip list` to see if the pacakge is properly installed.
- You can try cloning/downloading the source and install with `python -m pip install .` from the root of the source code directory.
- Mostly: use a virtual environment (see https://realpython.com/python-virtual-environments-a-primer/ if you are not familiar with virtual environments).

Hope this helps.
